name: Feature request
description: Request a new feature
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like
      description: |
        A clear and concise description of what you want to request.
        You can also attach screenshots or screen recordings to help explain your request.
    validations:
      required: true
